name: Terratest CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  terratest:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve

      - name: Set BUCKET_NAME environment variable
        run: |
          echo "BUCKET_NAME=$(terraform output -raw bucket_name)" >> $GITHUB_ENV

      - name: Run Terratest
        run: |
          go mod tidy
          go test -v ./test

      - name: Terraform Destroy
        if: always()
        run: terraform destroy -auto-approve
